(function (me){
//*************************	///選択されているコンポ配列を返す
	var getComp = function()	{		var ret = [];		if (app.project.selection.length>0) {			for (var i=0; i<app.project.selection.length; i++ ){				if (app.project.selection[i] instanceof CompItem) {					ret.push(app.project.selection[i]);				}			}		}		return ret;	}//*************************	//選択されたレイヤ配列を返す
	var getLayers = function()	{		var ret = [];		var ac = app.project.activeItem;				if (ac instanceof CompItem) {			if (ac.selectedLayers.length>0) {				ret = ac.selectedLayers;			}		}		return ret;	}//*************************//レイヤ内のP_anti-aliasingをindex番号配列で返すvar getPAA = function(lyr) {	var ret = [];	var fxg = lyr.property("ADBE Effect Parade");	if (fxg.numProperties>0){		for (var i=1; i<=fxg.numProperties;i++) {			if (fxg.property(i).matchName ==="PSOFT ANTI-ALIASING"){				if (fxg.property(i).enabled === true) {					ret.push(fxg.property(i).propertyIndex);				}			}		}	}		return ret;}//*************************	//　
	var toOLMS = function(p)	{		var ret = false;		if (p.matchName !="PSOFT ANTI-ALIASING") return ret;		var idx = p.propertyIndex;		var range = p.property(1).value *6/10;		var colOn = p.property(5).value;		var col = p.property(6).value;		var fxg = p.parentProperty;		if (fxg.canAddProperty("OLM Smoother")==true) {			var olms = fxg.addProperty("OLM Smoother");			if (olms !=null) {				var useCol = olms.property(1);				useCol.setValue(colOn);				var keyCol = olms.property(2);				keyCol.setValue(col);				var rangeCol = olms.property(3);				rangeCol.setValue(range);				fxg.property(idx).enabled = false;				olms.moveTo(idx+1);				ret = true;			}		}				return ret;	}	//*************************var undoAALayerSub = function(lyr){	var ret = false;	var fxg = lyr.property("ADBE Effect Parade");		if ( (fxg==null)||(fxg.numProperties<=1)) return ret;		for ( var i=fxg.numProperties-1; i>=1; i--){		var p1 = fxg.property(i);		var p2 = fxg.property(i+1);		if ( 				(p1.matchName == "PSOFT ANTI-ALIASING")			&&(p1.enabled == false)			&&(p2.matchName == "OLM Smoother")			&&(p2.enabled == true)) {				p1.enabled = true;				p2.remove();				ret = true;			}	}		return ret;}//*************************//レイヤ内のP_ColorSelectionをindex番号配列で返すvar getPCS = function(lyr) {	var ret = [];	var fxg = lyr.property("ADBE Effect Parade");	if (fxg.numProperties>0){		for (var i=1; i<=fxg.numProperties;i++) {			if (fxg.property(i).matchName ==="PSOFT COLORSELECTION"){				if (fxg.property(i).enabled === true) {					ret.push(fxg.property(i).propertyIndex);				}			}		}	}		return ret;}//*************************//P_ColorSelectionプロパティグループから色テーブルオブジェクトを返す。	var getColors = function(p)	{		var  ret = {};		ret.rev = false;		ret.tbl = [];		ret.count = 0;		ret.index = p.propertyIndex;		if ( (p.matchName !=="PSOFT COLORSELECTION")||(p.enabled === false)) return ret;		ret.rev = (p.property(2).value===1);		var view = p.property(1).value;		if (view <= 1) return ret;		//----		if ( (view==3)||(view==4) ){			if ( p.property(6).value ===1){				var sc = p.property(5).value * 4;				for ( var i= 0; i<sc; i++) {					var idx = 7 + i * 3;					if (p.property(idx).value === 1) {						ret.tbl.push(p.property(idx+1).value);					}				}			}		}		//----		if ( (view==3)||(view==5) ){			if ( p.property(59).value ===1){				var sc = p.property(58).value * 4;				for ( var i= 0; i<sc; i++) {					var idx = 60 + i * 3;					if (p.property(idx).value === 1) {						ret.tbl.push(p.property(idx+1).value);					}				}			}		}		ret.count = ret.tbl.length;		return ret;	}
//*************************	//　getColorsで得られたオブジェクトからF's SelectColorを作成
	var toFs = function(p)	{		var ret = false;		var idx = p.propertyIndex;		var fxg = p.parentProperty;		var ct = getColors(p);		if (ct.count<=0) return ret;		if (fxg.canAddProperty("F's SelectColor")==true) {			var fssc = fxg.addProperty("F's SelectColor");			if (fssc !=null) {				var rev = fssc.property(17);				rev.setValue(ct.rev);				for ( var i=0; i<ct.count; i++){					if (i>=8) {						alert("色数が8色超えています！");						break;					}					var  e = fssc.property(i*2+1);					e.setValue(true);					var c = fssc.property(i*2+2);					c.setValue(ct.tbl[i]);				}				fxg.property(idx).enabled = false;				fssc.moveTo(idx+1);				ret = true;			}		}				return ret;	}//*************************var execCSLayer = function(){	var lyrs = getLayers();	if (lyrs.length<=0) {		alert("レイヤが選択されていません！");		return;	}	var cnt = 0;	app.beginUndoGroup("P_SC対処レイヤー");	for ( var i=0; i<lyrs.length;i++){		var pcs = getPCS(lyrs[i]);		if (pcs.length>0) {			var fxg = lyrs[i].property("ADBE Effect Parade");			for ( var j=pcs.length -1 ; j>=0; j--) {				if (toFs(fxg.property(pcs[j]))) {					cnt++;				}			}		}	}	app.endUndoGroup();	alert(cnt +"箇所を対処");}//*************************var execCSComp = function(){	var comps = getComp();	if (comps.length<=0) {		alert("コンポが選択されていません！");		return;	}	var cnt = 0;	app.beginUndoGroup("P_SC対処コンポ");	for (var cc = 0; cc<comps.length; cc++) {		var cmp = comps[cc];		if (cmp.numLayers<=0) continue;				for ( var i=1; i<=cmp.numLayers;i++){			var pcs = getPCS(cmp.layer(i));			if (pcs.length>0) {				var fxg = cmp.layer(i).property("ADBE Effect Parade");				for ( var j=pcs.length -1 ; j>=0; j--) {					if (toFs(fxg.property(pcs[j]))) {						cnt++;					}				}			}		}	}		app.endUndoGroup();	alert(cnt +"箇所を対処");}
//*************************var undoCSLayerSub = function(lyr){	var ret = false;	var fxg = lyr.property("ADBE Effect Parade");		if ( (fxg==null)||(fxg.numProperties<=1)) return ret;		for ( var i=fxg.numProperties-1; i>=1; i--){		var p1 = fxg.property(i);		var p2 = fxg.property(i+1);		if ( 				(p1.matchName == "PSOFT COLORSELECTION")			&&(p1.enabled == false)			&&(p2.matchName == "F's SelectColor")			&&(p2.enabled == true)) {				p1.enabled = true;				p2.remove();				ret = true;			}	}		return ret;}//*************************var undoCSLayer = function(){	var lyrs = getLayers();	if (lyrs.length<=0) {		alert("レイヤが選択されていません！");		return;	}	var cnt = 0;	app.beginUndoGroup("P_SC対処レイヤーアンドー");	for ( var i=0; i<lyrs.length;i++){		if  ( undoCSLayerSub(lyrs[i])) {			cnt++;		}	}	app.endUndoGroup();	alert(cnt +"箇所を対処");	}//*************************var undoCSComp = function(){	var comps = getComp();	if (comps.length<=0) {		alert("コンポが選択されていません！");		return;	}	var cnt = 0;	app.beginUndoGroup("P_SC対処コンポ アンドー");	for (var cc = 0; cc<comps.length; cc++) {		var cmp = comps[cc];		if (cmp.numLayers<=0) continue;				for ( var i=1; i<=cmp.numLayers;i++){			if  ( undoCSLayerSub(cmp.layer(i))) {				cnt++;			}		}	}		app.endUndoGroup();	alert(cnt +"箇所を対処");}//*************************
var execAALayer = function(){	var lyrs = getLayers();	if (lyrs.length<=0) {		alert("レイヤが選択されていません！");		return;	}	var cnt = 0;	app.beginUndoGroup("P_AA対処レイヤー");	for ( var i=0; i<lyrs.length;i++){		var paa = getPAA(lyrs[i]);		if (paa.length>0) {			var fxg = lyrs[i].property("ADBE Effect Parade");			for ( var j=paa.length -1 ; j>=0; j--) {				if (toOLMS(fxg.property(paa[j]))) {					cnt++;				}			}		}	}	app.endUndoGroup();	alert(cnt +"箇所を対処");}
//*************************var undoAALayer = function(){	var lyrs = getLayers();	if (lyrs.length<=0) {		alert("レイヤが選択されていません！");		return;	}	var cnt = 0;	app.beginUndoGroup("P_AA対処レイヤーアンドー");	for ( var i=0; i<lyrs.length;i++){		if  ( undoAALayerSub(lyrs[i])) {			cnt++;		}	}	app.endUndoGroup();	alert(cnt +"箇所を対処");	}//*************************var execAAComp = function(){	var comps = getComp();	if (comps.length<=0) {		alert("コンポが選択されていません！");		return;	}	var cnt = 0;	app.beginUndoGroup("P_AA対処コンポ");	for (var cc = 0; cc<comps.length; cc++) {		var cmp = comps[cc];		if (cmp.numLayers<=0) continue;		for ( var i=1; i<=cmp.numLayers;i++){			var paa = getPAA(cmp.layer(i));			if (paa.length>0) {				var fxg = cmp.layer(i).property("ADBE Effect Parade");				for ( var j=paa.length -1 ; j>=0; j--) {					if (toOLMS(fxg.property(paa[j]))) {						cnt++;					}				}			}		}	}		app.endUndoGroup();	alert(cnt +"箇所を対処");}
//*************************var undoAAComp = function(){	var comps = getComp();	if (comps.length<=0) {		alert("コンポが選択されていません！");		return;	}	var cnt = 0;	app.beginUndoGroup("P_AA対処コンポ アンドー");	for (var cc = 0; cc<comps.length; cc++) {		var cmp = comps[cc];		if (cmp.numLayers<=0) continue;				for ( var i=1; i<=cmp.numLayers;i++){			if  ( undoAALayerSub(cmp.layer(i))) {				cnt++;			}		}	}		app.endUndoGroup();	alert(cnt +"箇所を対処");}//*************************//MainWindow
var winObj = ( me instanceof Panel) ? me : new Window("palette", "psoft プラグインイがない時に", [0,0,0+310,0+320],{resizeable:false});

//*************************
//controls
var gbColorSelection = winObj.add("panel",[11, 11, 11+288, 11+146],"P_ColorSelectionをF's SelectColorに置き換えます");
var btnCLayer = gbColorSelection.add("button",[12, 24, 12+264, 24+23],"レイヤーに対処");
var btnCUndoLayer = gbColorSelection.add("button",[12, 53, 12+264, 53+23],"元に戻す(lレイヤ)");
var btnCComp = gbColorSelection.add("button",[12, 82, 12+264, 82+23],"コンポに対処");
var btnCUndoComp = gbColorSelection.add("button",[12, 111, 12+264, 111+23],"元に戻す(コンポ)");
var groupBox = winObj.add("panel",[11, 163, 11+288, 163+146],"anti-aliasingをOLM smootherに置き換えます。");
var btnALayer = groupBox.add("button",[12, 24, 12+264, 24+23],"レイヤーに対処");
var btnAUndoLayer = groupBox.add("button",[12, 53, 12+264, 53+23],"元に戻す(lレイヤ)");
var btnAComp = groupBox.add("button",[12, 82, 12+264, 82+23],"コンポに対処");
var btnAUndoComp = groupBox.add("button",[12, 111, 12+264, 111+23],"元に戻す(コンポ)");

//*************************
//button click event
btnCLayer.onClick = execCSLayer;
btnCComp.onClick = execCSComp;
btnCUndoLayer.onClick = undoCSLayer;
btnCUndoComp.onClick = undoCSComp;
//btnALayer.onClick = execAALayer;btnAUndoLayer.onClick = undoAALayer;btnAComp.onClick = execAAComp;btnAUndoComp.onClick = undoAAComp
//*************************
//window show
	if ( ( me instanceof Panel) == false){
		winObj.center();
		winObj.show();
	}
})(this);
