
(function(me){

	//-------------------------------------------------------------------------
	var winObj = ( me instanceof Panel) ? me : new Window("palette", "replaceCornerPin", [ 0,  0,  250,  150]  ,{resizeable:true, maximizeButton:true, minimizeButton:true});
	//-------------------------------------------------------------------------
	var stCaption = winObj.add("statictext", [  10,   10,   10+ 230,   10+  18], "コーナーピンとCC Power Pinを入れ替えます");
	var pnlMode = winObj.add("panel", [  10,   30,   10+ 230,   30+  68], "mode" );
	var rbToDefault = pnlMode.add("radiobutton", [  10,   10,   10+ 210,   10+  24], "コーナーピンへ");
	var rbToCC = pnlMode.add("radiobutton", [  10,   34,   10+ 210,   34+  24], "CC Power Pinへ");
	var btnExec = winObj.add("button", [  10,  100,   10+ 230,  100+  30], "btnExec" );
	rbToDefault.value = true;
	//-------------------------------------------------------------------------	var getKeys = function(prop)	{		var ret = {};		ret.ok = false;		ret.isArray = false;		if ( prop instanceof Property){					if ( prop.numKeys <=0){				ret.value = prop.value;				ret.ok = true;				ret.isArray = false;			}else{				ret.value = [];				for (var i =1; i<=prop.numKeys;i++){					var p = {};					p.time = prop.keyTime(i);					p.value = prop.keyValue(i);					ret.value.push(p);				}				ret.ok = true;				ret.isArray = true;							}				}		return ret;	}	//-------------------------------------------------------------------------	var setKeys = function(prop,p)	{		if ( !(prop instanceof Property)) return;		if (p.ok === false) return;		if (prop.numKeys>0){			for ( var i = prop.numKeys; i >= 1; i--) prop.removeKey(i);		}		if (p.isArray === false){			prop.setValue(p.value);		}else{			for ( var i= 0; i<p.value.length; i++){				prop.setValueAtTime(p.value[i].time,p.value[i].value); 			}		}	}	//-------------------------------------------------------------------------	var execToDef =function(prop)	{		if ( prop.matchName !== "CC Power Pin") return false;				var idx = prop.propertyIndex;		var TopLeft		= getKeys( prop.property("CC Power Pin-0002") );		var TopRight		= getKeys( prop.property("CC Power Pin-0003") );		var BottomLeft	= getKeys( prop.property("CC Power Pin-0004") );		var BottomRight	= getKeys( prop.property("CC Power Pin-0005") );			var pp = prop.parentProperty;		prop.remove();		var np = pp.addProperty("ADBE Corner Pin");		setKeys(np.property("ADBE Corner Pin-0001"),TopLeft);
		setKeys(np.property("ADBE Corner Pin-0002"),TopRight);
		setKeys(np.property("ADBE Corner Pin-0003"),BottomLeft);
		setKeys(np.property("ADBE Corner Pin-0004"),BottomRight);		np.moveTo(idx);		return true;	}	//-------------------------------------------------------------------------	var execToCC =function(prop)	{		if ( prop.matchName !== "ADBE Corner Pin") return false;				var idx = prop.propertyIndex;		var TopLeft		= getKeys( prop.property("ADBE Corner Pin-0001") );		var TopRight		= getKeys( prop.property("ADBE Corner Pin-0002") );		var BottomLeft	= getKeys( prop.property("ADBE Corner Pin-0003") );		var BottomRight	= getKeys( prop.property("ADBE Corner Pin-0004") );			var pp = prop.parentProperty;		prop.remove();		var np = pp.addProperty("CC Power Pin");		setKeys(np.property("CC Power Pin-0002"),TopLeft);
		setKeys(np.property("CC Power Pin-0003"),TopRight);
		setKeys(np.property("CC Power Pin-0004"),BottomLeft);
		setKeys(np.property("CC Power Pin-0005"),BottomRight);		np.moveTo(idx);		return true;	}	//-------------------------------------------------------------------------	var exec = function()	{		var findName = function(a,n)		{			var ret = false;			if ( a.length>0){				for (var i=0; i<a.length; i++){					if (a[i].name === n){						ret = true;						break;					}				}			}			return ret;		}		var ac = app.project.activeItem;		if ( !( ac instanceof CompItem)) {			alert("コンポをアクティブにしてください。")			return;		}		var sp = ac.selectedProperties;		if ( sp.length <=0 ) {			alert("プロパティを選んでください")			return;		}				var isToDef = rbToDefault.value;		var targetMatchName = "";		if ( isToDef === true){			targetMatchName = "CC Power Pin";		}else{			targetMatchName = "ADBE Corner Pin";		}				var targets = [];		for (var i=0; i<sp.length; i++){			if ( sp[i] instanceof PropertyGroup){				if (sp[i].matchName === targetMatchName)					targets.push(sp[i]);			}else if ( sp[i] instanceof Property){				var pp = sp[i].parentProperty;				if ( findName(targets,pp.name) === false){					if (sp[i].matchName === targetMatchName)						targets.push(pp);				}			}		}				if (targets.length>0){			var cnt = 0;			app.beginUndoGroup("replace Corner Pin");			for ( var i=0; i<targets.length; i++){				if (isToDef){					if (execToDef(targets[i]) ) cnt++;				}else{					if (execToCC(targets[i]) ) cnt++;				}			}			app.endUndoGroup();			if (cnt === 0){				alert("処理されませんでした。")			}		}else{			alert("有効なプロパティを選んでください")		}	}	btnExec.onClick = exec;	//-------------------------------------------------------------------------	var resizeWin = function()	{		var b = winObj.bounds;		var w = b[2]-b[0] -20;		var pb = pnlMode.bounds;		pb[2] = b[2] - 10;		pnlMode.bounds = pb;				var bb = btnExec.bounds;		bb[2] = b[2] - 10;		btnExec.bounds = bb;			}	resizeWin();	winObj.onResize = resizeWin;
	//-------------------------------------------------------------------------
	if ( ( me instanceof Panel) == false){
		winObj.center(); 
		winObj.show();
	}
	//-------------------------------------------------------------------------
})(this);